### ISSUE TITLE
MS Edge throws an error when loading landscape.cncf.io

### ISSUE THREAD

**Issue by jordinl83** [cncf/landscapeapp#326]
![Screenshot 2019-09-09 at 16 11 45](https://user-images.githubusercontent.com/16135423/64541340-005db200-d322-11e9-9fc5-feeffd970c60.png)

**Comment by jordinl83** [comment]
@dankohn seems that the issue was fixed when all the dependencies were updated:

![VirtualBox_MSEdge - Win10_26_09_2019_15_44_07](https://user-images.githubusercontent.com/16135423/65693508-af192680-e074-11e9-892f-a0eda6fea8e9.png)

**Comment by dankohn** [comment]
Resolved

**Comment by Sanghshree** [comment]
Hi all , I am running into the same issue , where I getting the above error on edge , and as, per earlier solution , I updated all the dependencies , but still getting same error. Can someone from this group help me understand what all dependencies are required to update or provide some solution for this issue.

Thanks

**Comment by dankohn** [comment]
Can you please paste in the results from https://debug.thetwopercent.co.uk/

**Comment by Sanghshree** [comment]
[
![IE error](https://user-images.githubusercontent.com/35825979/88185101-882e7100-cc01-11ea-8a9b-9b0b040555ba.PNG)
](url)

**Comment by dankohn** [comment]
What about when you go to https://landscape.lfph.io.

**Comment by Sanghshree** [comment]
Hi Dankon, 
 when I go tot https://landscape.lfph.io/ it works , however, it does not work on our company server when deployed , just wanted understand , if there are any required configurations which we might be missing.

**Comment by jordinl83** [comment]
@Sanghshree are you using a recent version of MS Edge? I've tried some of our landscapes from [landscapes.dev](https://landscapes.dev) and they all work fine

**Comment by Sanghshree** [comment]
Hi Jordin, 

We are using Microsoft Edge 44.17763.831.0 version ,
Microsoft EdgeHTML 18.17763 

what version of MS edge is compatible with cncf landscapes.
Alsp , for more clarity , landscapes works on the MS edge in dev environment , however when its packaged and  deployed , the deployed version doesnot work on MS edge. I hope this information helps.

**Comment by jordinl83** [comment]
@Sanghshree I think that is an old version of MS Edge. The version I used for testing is 84.0.522.40. We only support modern browsers. Is it possible to upgrade MS Edge?

**Comment by Sanghshree** [comment]
@jordinl83 Thanks for the update.

**Comment by dankohn** [comment]
Closing for now
